# Generated by Django 4.0.4 on 2022-08-05 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('outcome', models.TextField()),
                ('requirement', models.TextField()),
                ('description', models.TextField()),
                ('course_type', models.CharField(default='Free', max_length=30)),
                ('fee', models.IntegerField(blank=True, default=0, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_count', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.FloatField(default=0)),
                ('number_of_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=0, max_length=30)),
                ('course_id', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('description', models.CharField(blank=True, max_length=555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(default=0)),
                ('course_id', models.IntegerField(default=0)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
                ('gender', models.CharField(default='Other', max_length=30)),
                ('date_of_birth', models.CharField(default='00-00-00', max_length=60)),
                ('account_type', models.CharField(default='Student', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=300)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
