# Generated by Django 4.0.4 on 2022-05-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=20)),
            ],
        ),
    ]
