# Generated by Django 4.0.4 on 2022-08-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_sold',
            field=models.IntegerField(default=0),
        ),
    ]
