# Generated by Django 4.0.4 on 2022-08-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseType',
            new_name='course_type',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Random', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
