# Generated by Django 4.0.4 on 2022-05-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_date_of_birth_user_gender_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
