# Generated by Django 4.0.4 on 2022-05-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='types',
            new_name='account_type',
        ),
    ]
