# Generated by Django 4.0.4 on 2022-06-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('outcome', models.TextField()),
                ('requirement', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
