# Generated by Django 4.0.4 on 2022-06-13 22:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, default=1, size=None),
            preserve_default=False,
        ),
    ]
