# Generated by Django 4.0.4 on 2022-06-13 22:58

import base.models
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_course_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=base.models.Video(blank=True), blank=True, size=None),
        ),
    ]
